import sys

dna = "CGATGTGCGCCATAACACACGTCCGGCCCCCGTTGGTACTCGGATATCAAGCTGAATCGAATACGCGCCAGCGAGATGTGAGCTCTATATTTTACGACGTAGTCATACAGCCGCGTCGATAGTTTGACCCATTCAGCGCGGAGTGGGTGCGTTGTATTTCTGGAACAGCGGTTCCTCGTTTAGCCCGTCAGTAGTGCATTTTGCCCCTCAGAATAATCGTGGCACGGTATAGCATGGCCGTAGGTGGTAAACCTCAATAGACCCGCCGGAATAAGAAACTTTCAAGCAGTGTTAAGGAGAATTAAAACATGCGCTATGTAAAGGCAGCTTTCCTATAGCTGGAAATGAATCCCATTTCTTTAGGTACCTCGTGTCGAATGGCGCGTGAATCCGTCGTAGGCGGGTTACCTGGTGCATACTCTTCTTTCATTGTTGGTTGGATCTATAATCTCAGTTATCTGAAGTAGAGGATTAGGGAAACTGGGAATATGTTTCCAGTAAGGCGGGAGGTTAATGATTGTCGCTGTCCTTCAGTTCAGGTAGGTAAGTCTCGGCGCTATGCATTGCTACTTCTGTAATCTTAAATCACCGAAGTTATGGTTTTTAATCCAATCGACGCCTGGGTCATAAGAGTGTGCGCCCGGAAGAACCGAGTTAACAAATTCGATCTTTACCGCCACAGGATAACACGAACCCTCGTTTCATCTTGGTTTACCCCGGCGCTTCGGTTTGTAGGCCACTGTGGGGTAGGCAAGATTAGTTCTTCGAGGCAGCATAGCATTGCTCTATTTTGTATCACGCTCCCAGTAGATACCCCGCCTGCTGTTGAACGGGGTAGGTTGTTAGCTACGAGCGCGTGACGTAAATATGAAATGTTCATTGCCCCGAGGGCCGACCC"


def readFile(filename):
    with open(filename, 'r') as file:
        contents = file.read().replace('\n', '')
    return contents


if __name__ == '__main__':
    if len(sys.argv) >= 2:
        dna = readFile(sys.argv[1])

    dna = dna.upper()
    print '{:d} {:d} {:d} {:d}'.format(dna.count('A'), dna.count('C'), dna.count('G'), dna.count('T'))
